name = "aho_corasick"
description = "Aho-Corasick Implementation"
version = "0.1.0-dev"

authors = ["docandrew"]
maintainers = ["docandrew <19672868+docandrew@users.noreply.github.com>"]
maintainers-logins = ["docandrew"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

# project-files = ["aho_corasick.gpr", "sparklib.gpr"]

[[depends-on]]
gnatprove = "^15.1.0"

